/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import deflater.MyDeflater;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;

/**
 * @author Сеня
 */
public class GUI extends javax.swing.JFrame {
    JPanel jPanel2 = new JPanel();
    JLabel jLabel1 = new JLabel();
    JTextField jTextField1 = new javax.swing.JTextField();
    // Variables declaration - do not modify
    JButton jButtonFCh = new JButton();
    JLabel jLabel2 = new JLabel();
    JButton jButtonStart = new JButton();
    JLabel jLabel3 = new JLabel();
    JLabel jLabel4 = new JLabel();
    JTextField jTextField2 = new JTextField();
    JButton jButtonFCh1 = new JButton();
    JLabel jLabel5 = new JLabel();
    JButton jButtonStart1 = new JButton();
    JLabel jLabel6 = new JLabel();
    JTextField jTextField3 = new JTextField();
    JLabel jLabel7 = new JLabel();
    JTextField jTextField4 = new JTextField();
    JLabel jLabel8 = new JLabel();
    JButton jButtonFCh2 = new JButton();
    JButton jButtonFCh3 = new JButton();

    String fileChooserTitle;
    String compressedFileName;
    String uncompressedFileName;
    int fileSize;
    int compressedFileSize;
    boolean check = true;


    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Архиватор А1");
        setBackground(new java.awt.Color(255, 255, 0));
        setFont(new java.awt.Font("Aharoni", Font.BOLD, 18)); // NOI18N
        setPreferredSize(new java.awt.Dimension(320, 400));

        jLabel1.setText("Выберите файл для архивации");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButtonFCh.setIcon(new javax.swing.ImageIcon("C:\\Users\\Сеня\\Downloads\\klipartz.com (1).png")); // NOI18N
        jButtonFCh.addActionListener(this::jButtonFChActionPerformed);


        jLabel2.setVisible(false);

        jButtonStart.setText("Старт");
        jButtonStart.addActionListener(this::jButtonStartActionPerformed);

        jLabel3.setText("Выберите папку для сохранения  сжатого файла");


        jLabel4.setVisible(false);

        jTextField2.setSelectionColor(new java.awt.Color(51, 153, 255));
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jButtonFCh1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Сеня\\Downloads\\klipartz.com (1).png")); // NOI18N
        jButtonFCh1.addActionListener(this::jButtonFCh1ActionPerformed);

        jLabel5.setText("Размер исходного файла: ");
        jLabel5.setVisible(false);

        jButtonStart1.setText("Старт");
        jButtonStart1.addActionListener(this::jButtonStart1ActionPerformed);

        jLabel6.setText("Выберите папку для сохранения  файла");

        jTextField3.setSelectionColor(new java.awt.Color(51, 153, 255));
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel7.setText("Выберите файл для разархивации");

        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jLabel8.setText("Размер расжатого файла: ");
        jLabel8.setVisible(false);

        jButtonFCh2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Сеня\\Downloads\\klipartz.com (1).png")); // NOI18N
        jButtonFCh2.addActionListener(this::jButtonFCh2ActionPerformed);

        jButtonFCh3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Сеня\\Downloads\\klipartz.com (1).png")); // NOI18N
        jButtonFCh3.addActionListener(this::jButtonFCh3ActionPerformed);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonStart)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonStart1)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonFCh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonFCh1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonFCh2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonFCh3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonFCh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonFCh1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonStart)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonFCh2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonFCh3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonStart1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButtonFChActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File(".")); //sets current directory

        int response = fileChooser.showOpenDialog(null); //select file to open
        //int response = fileChooser.showSaveDialog(null); //select file to save

        if (response == JFileChooser.APPROVE_OPTION) {
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            String absPth = file.getAbsolutePath();
            jTextField1.setText(absPth);
            compressedFileName = file.getName();
            fileSize = (int) (file.length() / 1024);

        }

    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonFCh1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();


        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setDialogTitle(fileChooserTitle);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        fileChooser.setAcceptAllFileFilterUsed(false);
        //
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String absPth = fileChooser.getSelectedFile().getAbsolutePath();
            jTextField2.setText(absPth);
        }
    }

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonFCh2ActionPerformed(ActionEvent e) {
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File(".")); //sets current directory

        int response = fileChooser.showOpenDialog(null); //select file to open
        //int response = fileChooser.showSaveDialog(null); //select file to save

        if (response == JFileChooser.APPROVE_OPTION) {
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            String absPth = file.getAbsolutePath();
            jTextField4.setText(absPth);
            String compressedFileName1 = file.getName();
            String[] splitName = compressedFileName1.split("\\$");
            uncompressedFileName = splitName[1];
            compressedFileSize = (int) (file.length() / 1024);

        }
    }

    private void jButtonFCh3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();


        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setDialogTitle(fileChooserTitle);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        fileChooser.setAcceptAllFileFilterUsed(false);
        //
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String absPth = fileChooser.getSelectedFile().getAbsolutePath();
            jTextField3.setText(absPth);
        }
    }

    private void jButtonStartActionPerformed(ActionEvent e) {
        // TODO add your handling code here:

        do {
            if (jTextField1.getText().equals("") && jTextField2.getText().equals("")) {
                check = false;
                JOptionPane.showMessageDialog(this, "Файл и папка не выбраны");
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                break;
            }
            if (jTextField1.getText().equals("")) {
                check = false;
                JOptionPane.showMessageDialog(this, "Файл не выбран");
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                break;
            }
            if (jTextField2.getText().equals("")) {
                check = false;
                JOptionPane.showMessageDialog(this, "Папка для сохранения не выбрана");
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                break;
            }
            File file = new File(jTextField2.getText() + "\\" + "def$"+compressedFileName);
            if (!file.exists()) {
                try {
                    MyDeflater.deflateFile(jTextField1.getText(), file.getAbsolutePath());
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
                int result = (int) Math.ceil(file.length()) / 1024;
                jLabel2.setText("Размер исх. файла: " + fileSize + " Кбайт");
                jLabel4.setText("Размер сжатого файла: " + result + " Кбайт");
                jLabel2.setVisible(true);
                jLabel4.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Файл сжат и находится в выбранной папке");
                break;
            }

        } while (check);
    }

    private void jButtonStart1ActionPerformed(ActionEvent e) {
        // TODO add your handling code here:
        do {
            if (jTextField4.getText().equals("") && jTextField3.getText().equals("")) {
                check = false;
                JOptionPane.showMessageDialog(this, "Файл и папка не выбраны");
                jLabel5.setVisible(false);
                jLabel8.setVisible(false);
                break;
            }
            if (jTextField4.getText().equals("")) {
                check = false;
                JOptionPane.showMessageDialog(this, "Файл не выбран");
                jLabel5.setVisible(false);
                jLabel8.setVisible(false);
                break;
            }
            if (jTextField3.getText().equals("")) {
                check = false;
                JOptionPane.showMessageDialog(this, "Папка для сохранения не выбрана");
                jLabel5.setVisible(false);
                jLabel8.setVisible(false);
                break;
            }
            File file = new File(jTextField3.getText() + "\\" + "inf$" + uncompressedFileName);
            if (!file.exists()) {
                try {
                    MyDeflater.inflateFile(jTextField4.getText(), file.getAbsolutePath());
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
                int result = (int) Math.ceil(file.length()) / 1024;
                jLabel5.setText("Размер сжатого файла: " + compressedFileSize + " Кбайт");
                jLabel8.setText("Размер расжатого файла: " + result + " Кбайт");
                jLabel5.setVisible(true);
                jLabel8.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Файл расжат и находится в выбранной папке");
                break;
            }
        } while (check);
    }
}
